[project]
name = 'backend'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []

[contracts.oracle-integration1]
path = 'contracts/oracle-integration1.clar'
clarity_version = 3
epoch = '3.2'


[contracts.time-lock-controller1]
path = 'contracts/time-lock-controller1.clar'
clarity_version = 3
epoch = 'latest'

[contracts.vault-manager1]
path = 'contracts/vault-manager1.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
